forum:
    jwt:
        expiration: 86400000
        secret: ${FORUM_JWT_SECRET}

info:
    app:
        description: '@project.description@'
        encoding: '@project.build.sourceEncoding@'
        java:
            version: '@java.version@'
        name: '@project.name@'
        version: '@project.version@'

management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: '*'

spring:
    datasource:
        username: ${POSTGRES_USER}
        url: ${SPRING_DATASOURCE_URL}${POSTGRES_DB}
        driverClassName: org.postgresql.Driver
        password: ${POSTGRES_PASSWORD}

    jpa:
        database: POSTGRESQL
        hibernate:
            ddl-auto: update
            naming:
                implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyHbmImpl
                physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgresPlusDialect
                jdbc:
                    lob:
                        non_contextual_creation: true
        show-sql: true

    mvc:
        pathmatch:
            matching-strategy: ANT_PATH_MATCHER
